### ISSUE TITLE
No Option To Redirect After Login ? Also Please add twitter login.

### ISSUE THREAD

**Issue by joomlaps** [LoginRadius/joomla-identity-extension#1]
No Option To Redirect After Login ? Also Please add twitter login.

**Comment by Agarwal-Sudhanshu** [comment]
Hi,
We have provided Redirection Option after Login in Joomla under extension section. 
All providers including Twitter can be managed from user account dashboard.
for more details, please visit https://docs.loginradius.com/
thanks
